routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@home')->middleware('guest')->name('home');
Route::get('/getapp','HomeController@getApp');
Auth::routes();
Route::group(['middleware'=>'auth'],function(){
	Route::group(['middleware'=>'regular','namespace'=>'PublicControllers'],function(){
		Route::get('/sell','SellingController@index')->name('sell');
		Route::post('/sell','SellingController@saveAuctionProduct');
		Route::get('/soldproducts', 'SellingController@sold')->name('sold');
		Route::get('/soldproducts/{id}', 'SellingController@soldProductDetails')->name('soldDetails');
		Route::post('/soldproducts/{id}/close', 'SellingController@soldProductClose')->name('soldClose');
		Route::post('/soldproducts/{id}/delete', 'SellingController@soldProductDelete')->name('soldDelete');
		Route::get('/buy','BuyingController@buy')->name('buy');
		Route::get('/buy/{id}','BuyingController@buyProduct')->name('buyProduct');
		Route::post('/buy/{id}','BuyingController@bidProduct')->name('bidProduct');
	});
	Route::group(['middleware'=>'admin','prefix'=>'admin','namespace'=>'AdminControllers'],function(){
		Route::get('/','AdminController@index')->name('adminHome');
		Route::get('/auctions','AdminController@allAuctions')->name('allAuctions');
		Route::post('/auctions/{id}/approve','AdminController@approve')->name('approve');
		Route::post('/auctions/approve/all','AdminController@approveall')->name('approveall');
	});

});

app/AuctionProducts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;

class AuctionProducts extends Model
{
    protected $table= "auctionproducts";
    protected $diff = 10;
    public function getProductNameAttribute($value)
    {
        return ucfirst($value);
    }
    protected $casts = [
        'approved' => 'boolean',
        'sold' => 'boolean',
    ];
    public function endDate()
    {
        return date('l d<\s\u\p>S</\s\u\p>, F Y \a\t h:i A',strtotime($this->end_date_time));
    }
    public function user(){
    	$user = $this->belongsTo('\App\User','user_id','id')->get()->first();
    	return $names = $user->firstname.' '.$user->lastname;
    }
    public function isValidForBid(){
        if ((strtotime($this->end_date_time) > time()) && $this->sold==0 && $this->user_id != Auth::user()->id) {
            return true;
        }
        return false;
    }
    public function bidPrice(){
        return $min = $this->highestBid()+$this->diff;
    }
    public function isEnded(){
        if (strtotime($this->end_date_time) < time()) {
            return true;
        }
        return false;
    }
    public function bids(){
        return $this->hasMany('App\Bids','product_id','id')->orderBy('price','desc')->get();
    }
    public function userBid(){
        return $this->hasMany('App\Bids','product_id','id')->where('user_id',Auth::user()->id)->get()->first();
    }
    public function apiUserBid($id){
        return $this->hasMany('App\Bids','product_id','id')->where('user_id',$id)->get()->first();
    }
    public function bidsCount(){
        return $this->hasMany('App\Bids','product_id','id')->get()->count();
    }
    public function highestBid(){
        return $this->hasMany('App\Bids','product_id','id')->get()->max('price');
    }
    public function isBidden(){
        if($this->hasMany('App\Bids','product_id','id')->get()->count()>0){
            return true;
        }
        else{
            return false;
        }
    }
    public function maxBid(){
        return $this->hasMany('App\Bids','product_id','id')->get()->max('price');
    }
    public function maxBidDetails(){
        return $this->hasMany('App\Bids','product_id','id')->where('price',$this->maxBid())->get()->first();
    }
    public function hasBidden(){
        if ($this->hasMany('App\Bids','product_id','id')->where('user_id',Auth::user()->id)->get()->count()==1) {
            return true;
        }
        return false;
    }
    public function apiHasBidden($id){
        if ($this->hasMany('App\Bids','product_id','id')->where('user_id',$id)->get()->count()==1) {
            return true;
        }
        return false;
    }
}

resources/views/buyProducts.blade.php
@extends('layouts.main')
@section('title') Bid products - @stop
@section('body')
<br>
@if(count($products)>0)
@foreach($products as $product)
<div class="row">
  <div class="col-md-3 text-center" style="position: relative;
    min-height: 90px;border-radius: 3px;
    border: 1px solid #e4e4e4;margin-left: 20px">
    <a href="#">
      <img class="" src="{{asset('img/products/'.$product->picture)}}" alt="..." style="margin: auto;width: auto;max-width: 100%;height: auto;max-height: 225px;display: block;text-align: center;">
    </a>
  </div>
  <div class="col-md-8">
    <h4 class="media-heading">{{$product->product_name}}</h4>
    <b>End on</b> {!!$product->endDate()!!}<br>
    <b>Initial price</b>: Rwf {{$product->minimal_price}}<br>
    @if($product->maxBid())
      <b>Highest bid: </b><u><b>Rwf {{$product->maxBid()}}</b></u>&nbsp;&nbsp;|&nbsp;&nbsp; 
      <span class="badge badge-default">{{$product->bidsCount() . '&nbsp;'.str_plural('Bid',$product->bidsCount())}}</span><br>
    @else
    <b class="text-muted">No bid yet</b><br>
    @endif
    {!! ($product->hasBidden())?'<b>Your bid</b>: Rwf '.$product->userBid()->price.'<br>':'' !!}
    <br>
    <b>Description: </b><p>{{$product->description}}</p><br>
    <a href="{{route('buyProduct',$product->id)}}"><button class="btn btn-primary btn-xs">{{($product->hasBidden())?'Rebid':'Bid'}} this product</button></a>
  </div>
</div><hr>
@endforeach
@else
<h2 class="text-center">No product to bid</h2>  
@endif
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('title') Home - @stop
@section('content')
    <div class="flex-center position-ref full-height">
        <div class="content">
            <div class="title">
                Auction | Sell & Buy
            </div>
        </div>
    </div>
@stop

resources/views/productView.blade.php
@extends('layouts.main')
@section('title') {{$product->product_name}} - @stop
@section('body')
<br>
@if(count($product)>0)
<div class="row">
  <div class="col-md-3 col-sm-6 text-center" style="position: relative;
    min-height: 90px;border-radius: 3px;
    border: 1px solid #e4e4e4;margin-left: 20px">
    <a href="#">
      <img class="" src="{{asset('img/products/'.$product->picture)}}" alt="..." style="margin: auto;width: auto;max-width: 100%;height: auto;max-height: 225px;display: block;text-align: center;">
    </a>
  </div>
  <div class="col-md-8 col-sm-6">
    <h4 class="media-heading">{{$product->product_name}}</h4>
    <b>End on</b> {!! $product->endDate() !!}<br>
    <b>Initial price</b>: Rwf {{$product->minimal_price}}<br>
    @if($product->maxBid())
      <b>Highest bid: </b><u><b>Rwf {{$product->maxBid()}}</b></u>&nbsp;&nbsp;|&nbsp;&nbsp; 
      <span class="badge badge-default">{{$product->bidsCount() . '&nbsp;'.str_plural('Bid',$product->bidsCount())}}</span><br>
    @else
    <b class="text-muted">No bid yet</b><br>
    @endif
    {!! ($product->hasBidden())?'<b>Your bid</b>: Rwf '.$product->userBid()->price.'<br>':'' !!}
    <br>
    <b>Description: </b><p>{{$product->description}}</p><br>
    <form method="post" action="{{ route('bidProduct',$product->id) }}" role="form" class="form-horizontal sell-form col-md-11 col-md-offset-1">
      {{csrf_field()}}
    <h4 class="text-center">Bid this product</h4>
    <hr>
    @if($product->hasBidden())
    <b class="text-info h4"><span class="ion-ios-information-outline"></span> &nbsp;Previous bid on this product:<b> Rwf {{$product->userBid()->price}}</b></b><br><br>
    @endif
    <p class="text-muted">Minimum price to bid is <b>Rwf {{($product->isBidden())?$product->maxBid()+10:$product->minimal_price}}</b></p>
    {!! (session()->has('message'))?'<b class="text-success h5">'.session()->get('message').'</b><br><br>':''!!}
    {!! (session()->has('errors'))?'<b class="text-danger h5">'.session()->get('errors')->first().'</b><br><br>':''!!}
    <br>
      <div class="form-group">
        <div class="col-md-4">Your price</div>
        <div class="col-md-8"><input type="number" name="price" value="{{($product->isBidden())?$product->maxBid()+10:$product->minimal_price}}"class="form-control" placeholder="Enter your bid price (in Rwf)..."/></div>
      </div>

      <div class="form-group text-center">
        <button class="btn btn-primary" type="submit">{{($product->hasBidden())?'Rebid':'Bid'}}</button>
      </div>
    </form>
  </div>
</div>
@else
<h2 class="text-center">No product found</h2>  
@endif
@endsection

resources/views/sellProduct.blade.php
@extends('layouts.main')
@section('title') Sell product - @stop
@section('body')
<br>
    <form class="form-horizontal sell-form col-md-11 col-md-offset-1" role="form" method="POST" action="{{ url('sell') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="text-center text-success">{!! session()->has('message')?session()->get('message')."<br><br>":"" !!}</div>

        <div class="form-group{{ $errors->has('productName') ? ' has-error' : '' }}">
            <label for="productName" class="col-md-3 control-label">Product name</label>

            <div class="col-md-8">
                <input id="productName" type="text" class="form-control" name="productName" value="{{ old('productName') }}" placeholder="Product name..." required autofocus>

                @if ($errors->has('productName'))
                    <span class="help-block">
                        <strong>{{ $errors->first('productName') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group{{ $errors->has('minimalPrice') ? ' has-error' : '' }}">
            <label for="minimalPrice" class="col-md-3 control-label">Minimal price</label>

            <div class="col-md-8">
                <input id="minimalPrice" type="number" class="form-control" name="minimalPrice" value="{{ old('minimalPrice') }}" placeholder="Minimal price (in Rwf)..." required>

                @if ($errors->has('minimalPrice'))
                    <span class="help-block">
                        <strong>{{ $errors->first('minimalPrice') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group{{ $errors->has('auctionEndTime') ? ' has-error' : '' }}">
            <label for="auctionEndTime" class="col-md-3 control-label">Auction end date</label>
            <div class="col-md-8{{ $errors->has('auctionEndTime') ? ' has-error' : '' }}">
                <input id="auctionEndTime" type='text' class="form-control" name="auctionEndTime" placeholder="Auction end time" autocomplete="off" />

                @if ($errors->has('auctionEndTime'))
                    <span class="help-block">
                        <strong>{{ $errors->first('auctionEndTime') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group{{ $errors->has('productPicture') ? ' has-error' : '' }}">
            <label for="productPicture" class="col-md-3 control-label">Product picture</label>

            <div class="col-md-8">
                <input id="productPicture" type="file" class="form-control" name="productPicture" value="{{ old('productPicture') }}">

                @if ($errors->has('productPicture'))
                    <span class="help-block">
                        <strong>{{ $errors->first('productPicture') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
            <label for="description" class="col-md-3 control-label">Product description</label>

            <div class="col-md-8">
                <textarea id="description" type="text" class="form-control" name="description" placeholder="Product description...">{{ old('description') }}</textarea> 

                @if ($errors->has('description'))
                    <span class="help-block">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-8 col-md-offset-1 text-left">
                <p>
                    * Please fill accurate information about the product you are going to sell 
                </p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-center">
            <br><br>
                <button type="submit" class="btn btn-primary">
                    Sell product
                </button>
            </div>
        </div>
    </form>
    @section('bottom_scripts')
        <script src="{{ asset('js/moment.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
        <script type="text/javascript">
            $(function () {
                $('#auctionEndTime').datetimepicker({
                    //locale:'ru',
                    useCurrent: false,
                    minDate:moment().add(2,'days'),
                    maxDate:moment().add(720,'days'),
                    format: 'YYYY-MM-DD HH:m',
                    
                });
            });
    </script>
    @endsection
@endsection

resources/views/soldProductDetails.blade.php
@extends('layouts.main')
@section('title') {{$product->product_name}} - @stop
@section('body')
<br>
@if(count($product)>0)
<div class="row">
  <div class="col-md-3 col-sm-6 text-center" style="position: relative;
    min-height: 90px;border-radius: 3px;
    border: 1px solid #e4e4e4;margin-left: 20px">
    <a href="#">
      <img class="" src="{{asset('img/products/'.$product->picture)}}" alt="..." style="margin: auto;width: auto;max-width: 100%;height: auto;max-height: 225px;display: block;text-align: center;">
    </a>
  </div>
  <div class="col-md-8 col-sm-6">
    <h4 class="media-heading">{{$product->product_name}}</h4>
    <b>End on</b> {!! $product->endDate() !!}<br>
    <b>Initial price</b>: Rwf {{$product->minimal_price}}<br>
    @if($product->maxBid())
      <b>Highest bid: </b><u><b>Rwf {{$product->maxBid()}}</b></u>&nbsp;&nbsp;|&nbsp;&nbsp; 
      <span class="badge badge-default">{{$product->bidsCount() . '&nbsp;'.str_plural('Bid',$product->bidsCount())}}</span><br>
    @else
    <b class="text-muted">No bid yet</b><br>
    @endif
    {!! ($product->hasBidden())?'<b>Your bid</b>: Rwf '.$product->userBid()->price.'<br>':'' !!}
    <br>
    <b>Description: </b><p>{{$product->description}}</p><br>
    <form method="post" action="{{ route('bidProduct',$product->id) }}" role="form" class="form-horizontal sell-form col-md-11 col-md-offset-1">
      {{csrf_field()}}
    <h4 class="text-center">Bid this product</h4>
    <hr>
    @if($product->hasBidden())
    <b class="text-info h4"><span class="ion-ios-information-outline"></span> &nbsp;Previous bid on this product:<b> Rwf {{$product->userBid()->price}}</b></b><br><br>
    @endif
    <p class="text-muted">Minimum price to bid is <b>Rwf {{($product->isBidden())?$product->maxBid()+10:$product->minimal_price}}</b></p>
    {!! (session()->has('message'))?'<b class="text-success h5">'.session()->get('message').'</b><br><br>':''!!}
    {!! (session()->has('errors'))?'<b class="text-danger h5">'.session()->get('errors')->first().'</b><br><br>':''!!}
    <br>
      <div class="form-group">
        <div class="col-md-4">Your price</div>
        <div class="col-md-8"><input type="number" name="price" value="{{($product->isBidden())?$product->maxBid()+10:$product->minimal_price}}"class="form-control" placeholder="Enter your bid price (in Rwf)..."/></div>
      </div>

      <div class="form-group text-center">
        <button class="btn btn-primary" type="submit">{{($product->hasBidden())?'Rebid':'Bid'}}</button>
      </div>
    </form>
  </div>
</div>
@else
<h2 class="text-center">No product found</h2>  
@endif
@endsection

resources/views/soldProducts.blade.php
@extends('layouts.main')
@section('title') My auctions - @stop
@section('body')
<br>
@if(count($products)>0)
@foreach($products as $product)
<div class="row">
  <div class="col-md-3 text-center" style="position: relative;
    min-height: 90px;border-radius: 3px;
    border: 1px solid #e4e4e4;margin-left: 20px">
    <a href="#">
      <img class="" src="{{asset('img/products/'.$product->picture)}}" alt="..." style="margin: auto;width: auto;max-width: 100%;height: auto;max-height: 225px;display: block;text-align: center;">
    </a>
  </div>
  <div class="col-md-8">
    <h4 class="media-heading"><a href="{{route('soldDetails',$product->id)}}">{{$product->product_name}}</a></h4>
    <b>End time</b>: {!!$product->endDate()!!}<br>
    <b>Initial Price</b>: Rwf {{$product->minimal_price}}<br>
    @if($product->maxBid())
      <b>Highest bid: </b><u><b>Rwf {{$product->maxBid()}}</b></u>&nbsp;&nbsp;|&nbsp;&nbsp; 
      <span class="badge badge-default">{{$product->bidsCount() . '&nbsp;'.str_plural('Bid',$product->bidsCount())}}</span><br>
    @else
    <b class="text-muted">No bid yet</b><br>
    @endif
    <b>Status</b>: {{($product->approved)?'Proved':'Pending'}}  
    {!! ($product->sold || $product->isEnded())?' | <span class="badge badge-danger">Auction closed</span>':'' !!}
    <br>
    <br>
    <b>Description: </b><p>{{$product->description}}</p><br>
  </div>
</div><hr>
@endforeach
@else
<div class="h1 text-center">You have not yet sold any product</div>
<div class="text-center"><a href="{{route('sell')}}"><button class="btn btn-primary">Start selling   your product</button></a></div>
@endif
@endsection

resources/views/soldProductsDetails.blade.php
@extends('layouts.main')
@section('title') {{$product->product_name}} - @stop
@section('body')
<br>
@if(count($product)>0)
<div class="row">
  <div class="col-md-3 col-sm-6 text-center" style="position: relative;
    min-height: 90px;border-radius: 3px;
    border: 1px solid #e4e4e4;margin-left: 20px">
    <a href="#">
      <img class="" src="{{asset('img/products/'.$product->picture)}}" alt="..." style="margin: auto;width: auto;max-width: 100%;height: auto;max-height: 225px;display: block;text-align: center;">
    </a>
  </div>
  <div class="col-md-8 col-sm-12">
    <h4 class="media-heading">{{$product->product_name}}</h4>
    <b>End on</b> {!! $product->endDate() !!}<br>
    <b>Initial price</b>: Rwf {{$product->minimal_price}}<br>
    @if($product->maxBid())
      <b>Highest bid: </b><u><b>Rwf {{$product->maxBid()}}</b></u>&nbsp;&nbsp;|&nbsp;&nbsp; 
      <span class="badge badge-default">{{$product->bidsCount() . '&nbsp;'.str_plural('Bid',$product->bidsCount())}}</span><br>
    @else
    <b class="text-muted">No bid yet</b><br>
    @endif
    {!! ($product->hasBidden())?'<b>Your bid</b>: Rwf '.$product->userBid()->price.'<br>':'' !!}
    <b>Status</b>: {{($product->approved)?'Proved':'Pending'}}  
    {!! ($product->sold || $product->isEnded())?' | <span class="badge badge-danger">Auction closed</span>':'' !!}
    <br>
    <br>
    <b>Description: </b><p>{{$product->description}}</p><br>
    @if($product->isBidden() && !$product->sold)
        <div><p class="text-center">Close auction to stop bidding and get contact information of the top bidder<br><br>   
                
                    <button class="btn btn-danger btn-xs" data-toggle="modal" data-target=".confirmBox"> Close auction</button>
            
            </p>
        </div>
        <hr>
    @endif
    @if(!$product->isBidden())
        <div><p class="text-center">You may also delete this auction record because no one has bade on this product <br><br>
        <a href="{{route('soldDelete',$product->id)}}" onclick="event.preventDefault();document.getElementById('deleteAuction').submit();">
            <button class="btn btn-danger btn-xs"> Delete auction</button></p>
        </a>    
        <form id="deleteAuction" action="{{ route('soldDelete',$product->id) }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
        </div>
        <hr>
    @endif
    @if(session()->has('message'))
        <div class="text-center text-success">{{session()->get('message')}}</div><br>
    @endif
    @if($product->isBidden())
    <h3 class="text-center">Auction bids</h3>
<div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="auctions" data-cont="all">
    <thead>
    <tr>
        <th>#</th>
        <th>Names</th>
        <th>Bid price</th>
        <th>Date and Time</th>
    </tr>
    </thead>
    <tbody>
    <?php $a=1; ?>
    @foreach($product->bids() as $bid)
        <tr {!!($product->maxBid()==$bid->price)?'class="success" style="border-left:5px solid green;"':''!!}  {!! ($product->isBidden() && $product->sold)?'data-toggle="modal" data-target=".contactDetails" id="pointer"':''!!}>
            <td>{{$a}}</td>
            <td>{{$bid->user()->firstname.' '.$bid->user()->lastname}}</td>
            <td>Rwf {{$bid->price}}</td>
            <td>{!!$bid->date()!!}</td>
            
        </tr>
        <?php $a++; ?>
    @endforeach
    </tbody>

</table>
</div>
@else
<h3 class="text-center">No bids placed on this auction</h3>
@endif
@if($product->isBidden() && $product->sold)
<div class="modal fade contactDetails" tabindex="-1" role="dialog" {{--data-backdrop="static"--}}data-keyboard="false" aria-labelledby="boxTitle">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="boxTitle">Contact details of top bidder</h5>
      </div>
      <div class="modal-body">
      <?php $details = $product->maxBidDetails()->user(); ?>
        <b>Names</b>: {{$details->firstname. ' ' . $details->lastname}}<br>
        <b>Email</b>: {{$details->email}}<br>
        <b>Phone</b>: {{$details->phone}}<br>
      </div>
      <div class="modal-footer">
        <p>Use the above details to contact the top bidder to proceed with payment process</p>
      </div>
    </div>
  </div>
</div>
@endif

  </div>
</div>
@else
<h2 class="text-center">No product found</h2>  
@endif

<div class="modal fade confirmBox" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="boxTitle">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="boxTitle" onclick="$('.close').addClass('.disabled')">Delete?</h5>
      </div>
      <div class="modal-body">
        Do you really want to close this Auction,
        Users will no longer be able to bid again.<br>
        
        <br><br>
        <b class="text-warning">Note that this action can not be undone</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
        <a href="{{route('soldClose',$product->id)}}" onclick="event.preventDefault();document.getElementById('closeAuction').submit();"><button type="button" class="btn btn-danger btn-sm">Yes, Close</button></a>
      </div>
    </div>
  </div>
</div>
<form id="closeAuction" action="{{ route('soldClose',$product->id) }}" method="POST" style="display: none;">{{ csrf_field() }}</form>

@endsection